set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# resurrection
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'

# clipboard sync
set -g set-clipboard on
set -as terminal-features ',*:clipboard'

# mouse event
set -g mouse on

# Scroll 2 lines instead of 5 when using the mouse wheel (vi mode)
bind -T copy-mode-vi WheelUpPane select-pane \; send-keys -X -N 2 scroll-up
bind -T copy-mode-vi WheelDownPane select-pane \; send-keys -X -N 2 scroll-down

# increase scroll history
set -g history-limit 10000

# quick conf reload
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# pass-through `shift-enter`
set -s extended-keys always
set -as terminal-features 'xterm*:extkeys'

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Show pane numbers
set-option -g pane-border-status top
set-option -g pane-border-format "#[fg=cyan,bold] #P #[fg=default]| #[fg=white]#{b:pane_current_path} "

# Automatically renumber windows when one is closed
set -g renumber-windows on

# Set active pane border color
set -g pane-active-border-style fg=cyan
# Use a heavier line for the active pane
set -g pane-border-lines heavy

# Set the foreground/background color for the active window
set -g window-active-style fg=colour231,bg=default
# Set the foreground/background color for all other windows
set -g window-style fg=colour240,bg=default

# plugin manager
run '~/.tmux/plugins/tpm/tpm'
